### ISSUE TITLE
Swagger Generation Failing

### ISSUE THREAD

**Issue by CJamesKeller** [adrianplavka/typeswag#1]
Hello!
@adrianplavka ,

I have tried to get the swagger generation working and can't seem to quite get there -- could you take a look at this example repo and see where my issue may be?

https://github.com/CJamesKeller/typeswag-example

Thanks!

**Comment by adrianplavka** [comment]
Hello!

Thanks for the issue submit. I'll take a look at it right tomorrow and I'll let you know!

**Comment by adrianplavka** [comment]
I looked at the code and I love, that you tried to test the functionality to the maximum. So, a couple of things:

**Module aliases** are not being resolved. Your import at `index.ts`, where you include the `Example` controller, won't work, because this library doesn't look at `_moduleAliases` in `package.json` (or equivalent).

This could be a good issue to resolve.

To fix it, change the import from:
```typescript
import { Example } from '@controllers/index';
```
to: 
```typescript
import { Example } from './controllers';
 ```

This won't fix the whole generation, as there is a couple of things with the controller itself:

1. You don't have to annotate the class with `@Route` decorator from `typeswag`, as you've already registered the custom decorator from `routing-controllers` in your `generateSwagger.ts` file. Doing so would throw an error, as only one route decorator is allowed on a class.

2. Variable `example` in the `@Get` decorator won't get picked up by the generator & would show an `undefined` value in the Swagger file. It seems, that dynamic paths like this won't work. I would change it to a normal string.

3. Your method, which you annotate as a `@Get`, won't work - it won't get picked up by the generator. I would declare it as a normal method, like shown in the example usage.

Note, that these issues exists even in the `tsoa` package (as this library is clone of it) & would need to be addressed. If these issues are very important to you, I could look at it in depth. At least, the `_moduleAliases` issue is really a thing, that should be addressed.

**Comment by CJamesKeller** [comment]
Thank you for looking at my repo! I will try making the changes you recommend and get it working.

For my own learning, could you tell me how you were able to determine what the problems were? I would not have thought to take out the aliases, or that arrow-function methods would not be picked up.

**Comment by adrianplavka** [comment]
It just required a basic knowledge of how the library works inside. Based on that, I tried to look at things, that could cause the generation to not even pick up the class. 

The class had defined arrow functions, that weren't methods - I think the generation treats these as normal properties of a class (not as functions/methods), therefore it ignores them.

I thought it would resolve the problem, but it still didn't generate. It struck to me, that the import in `index.ts` was a bit unusual and I thought, that it has some problem with it. I've decided to change it - after that it just worked.

Anyways, if you have more questions, or if it still doesn't work, let me know, so I can close the issue.

**Comment by CJamesKeller** [comment]
Works great with those changes, thank you! I really appreciate you taking the time to answer my questions and help me out!

**Comment by adrianplavka** [comment]
@CJamesKeller 
Just an update - I checked `tsoa`'s documentation and module aliases are really supported!

What you have to do in your case, is to go to your `generateSwagger.ts` file and add an argument to the `generateSwaggerSpec` function. The second argument of that function is a `ts.CompilerOptions` object, where you can set options during generating.

So, your call would look something like:
```typescript
typeswag.generateSwaggerSpec(
    {
        outputDirectory: './dist/',
        entryFile: './index.ts',
        basePath: 'api/v1',
    }, 
    {
        baseUrl: ".",
        paths: {
            "@controllers/*": ["controllers/*"]
        }
    }
);
```

After that, change the import in your `index.ts` file and module aliases will work now!

I will work on a better README & even include this example.
